# Generated by Django 3.2.9 on 2022-06-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subtitle',
            field=models.CharField(default='', max_length=500, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_update',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Последнее изменение'),
        ),
    ]
