# Generated by Django 3.2.9 on 2022-06-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(verbose_name='История фонда')),
                ('content1', models.TextField(verbose_name='Текст 1 блока')),
                ('image1', models.ImageField(upload_to='about/%Y/%m/%d/', verbose_name='Картинка 1')),
                ('content2', models.TextField(verbose_name='Текст 2 блока')),
                ('image2_1', models.ImageField(upload_to='about/%Y/%m/%d/', verbose_name='Картинка 2_1')),
                ('image2_2', models.ImageField(upload_to='about/%Y/%m/%d/', verbose_name='Картинка 2_1')),
                ('content3', models.TextField(verbose_name='Текст 3 блока')),
                ('image3', models.ImageField(upload_to='about/%Y/%m/%d/', verbose_name='Картинка 3')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Инфо без раздела',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=95, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='album/%Y/%m/%d/', verbose_name='Фото')),
                ('published', models.DateField(db_index=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(max_length=95, unique=True)),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('content', models.TextField(verbose_name='Текст')),
                ('mini_content', models.TextField(max_length=90, verbose_name='Аннотация')),
                ('published', models.DateField(db_index=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='Заставка новости')),
                ('file', models.FileField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='Файл презентации в pdf')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Имя')),
                ('content', models.CharField(blank=True, max_length=40, null=True, verbose_name='Короткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='person/%Y/%m/%d/', verbose_name='Фото человека')),
                ('published', models.DateField(db_index=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Человека',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('content', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='works/%Y/%m/%d/', verbose_name='Заставка проекта')),
                ('file', models.FileField(blank=True, null=True, upload_to='works/%Y/%m/%d/', verbose_name='Файл презентации в pdf')),
                ('published', models.DateField(db_index=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Основной текст')),
                ('content', models.TextField(verbose_name='Доп текст')),
                ('image', models.ImageField(upload_to='other/%Y/%m/%d/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'Фото на главной',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d/', verbose_name='Фото')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientir_main.album')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['-album'],
            },
        ),
    ]
