# Generated by Django 3.2.9 on 2022-06-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orientir_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='about',
            name='history',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image2_1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image2_2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image3',
        ),
    ]
