# Generated by Django 3.2.9 on 2022-06-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orientir_main', '0002_auto_20220621_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Текст')),
                ('slug', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Портфель ссылок',
                'verbose_name_plural': 'Портфель ссылок',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientir_main.linksbag')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
