# Generated by Django 3.2.9 on 2022-06-24 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orientir_main', '0003_link_linksbag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientir_main.linksbag', verbose_name='Портфель'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='people',
            name='content',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='content',
            field=models.TextField(max_length=111, verbose_name='Доп текст'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Основной текст'),
        ),
    ]
