# Generated by Django 3.2.9 on 2022-06-24 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orientir_main', '0004_auto_20220624_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orientir_main.album'),
        ),
        migrations.AlterField(
            model_name='news',
            name='mini_content',
            field=models.TextField(max_length=93, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=63, verbose_name='Заголовок'),
        ),
    ]
