# Generated by Django 3.2.9 on 2022-06-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientir_main', '0005_auto_20220624_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='mini_content',
            field=models.TextField(max_length=120, verbose_name='Аннотация'),
        ),
    ]
