# Generated by Django 3.2.9 on 2022-06-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orientir_main', '0006_alter_news_mini_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orientir_main.album'),
        ),
    ]
